import api from './api';
export const getProducts = (params) => api.get('/products', { params });
export const getProduct = (id) => api.get(`/products/${id}`);
export const getByBarcode = (code) => api.get(`/products/barcode/${code}`);
export const getCategories = () => api.get('/products/categories');
export const getLowStock = () => api.get('/products/low-stock');
export const createProduct = (data) => api.post('/products', data);
export const updateProduct = (id, data) => api.put(`/products/${id}`, data);
export const deleteProduct = (id) => api.delete(`/products/${id}`);
export const adjustStock = (id, data) => api.post(`/products/${id}/adjust-stock`, data);
export const importProducts = (products) => api.post('/products/import', { products });
